#if os(macOS)
import Distributed
import DistributedXPC

/// 手写元数据表(§3.4 F5):替代 @XPCService 宏生成物。
/// 宏按"基名+标签"生成键,`set(_:forKey:in:)` 五个重载共用一键,
/// 生成物为重复字典条目(告警);手写去重后单条目即正确形态——
/// 五个重载的 thrownErrorType 同为 `RimeError`,查表语义不变。
extension RimeServiceRoot: XPCDistributedTargetMetadataProviding, XPCExportableActor {
  public static var xpcDistributedTargetMetadata: [String: XPCDistributedTargetMetadata] {
    [
      "serviceVersion()": .init(thrownErrorType: RimeError.self),
      "healthCheck()": .init(thrownErrorType: RimeError.self),
      "setNotificationSink()": .init(thrownErrorType: RimeError.self),
      "setup(with:)": .init(thrownErrorType: RimeError.self),
      "initialize(with:)": .init(thrownErrorType: RimeError.self),
      "finalize()": .init(thrownErrorType: RimeError.self),
      "startMaintenance(fullCheck::)": .init(thrownErrorType: RimeError.self),
      "isMaintenanceMode()": .init(thrownErrorType: RimeError.self),
      "joinMaintenanceThread()": .init(thrownErrorType: RimeError.self),
      "initializeDeployer(with:)": .init(thrownErrorType: RimeError.self),
      "prebuild()": .init(thrownErrorType: RimeError.self),
      "deploy()": .init(thrownErrorType: RimeError.self),
      "deploySchema(withID:)": .init(thrownErrorType: RimeError.self),
      "deployConfig(filename::versionKey::)": .init(thrownErrorType: RimeError.self),
      "syncUserData()": .init(thrownErrorType: RimeError.self),
      "createSession()": .init(thrownErrorType: RimeError.self),
      "findSession(with:)": .init(thrownErrorType: RimeError.self),
      "destroySession(with:)": .init(thrownErrorType: RimeError.self),
      "cleanupStaleSessions()": .init(thrownErrorType: RimeError.self),
      "cleanupAllSessions()": .init(thrownErrorType: RimeError.self),
      "processKey(keyCode::modifierMask::for:)": .init(thrownErrorType: RimeError.self),
      "commitComposition(for:)": .init(thrownErrorType: RimeError.self),
      "clearComposition(for:)": .init(thrownErrorType: RimeError.self),
      "commit(for:)": .init(thrownErrorType: RimeError.self),
      "status(for:)": .init(thrownErrorType: RimeError.self),
      "context(for:)": .init(thrownErrorType: RimeError.self),
      "option(named:for:)": .init(thrownErrorType: RimeError.self),
      "setOption(value::for:)": .init(thrownErrorType: RimeError.self),
      "property(named:for:)": .init(thrownErrorType: RimeError.self),
      "setProperty(value::for:)": .init(thrownErrorType: RimeError.self),
      "schemaList()": .init(thrownErrorType: RimeError.self),
      "currentSchema(for:)": .init(thrownErrorType: RimeError.self),
      "selectSchema(for:)": .init(thrownErrorType: RimeError.self),
      "openSchema()": .init(thrownErrorType: RimeError.self),
      "openConfig()": .init(thrownErrorType: RimeError.self),
      "close(config::)": .init(thrownErrorType: RimeError.self),
      "string(forKey:in:)": .init(thrownErrorType: RimeError.self),
      "int(forKey:in:)": .init(thrownErrorType: RimeError.self),
      "bool(forKey:in:)": .init(thrownErrorType: RimeError.self),
      "double(forKey:in:)": .init(thrownErrorType: RimeError.self),
      "item(forKey:in:)": .init(thrownErrorType: RimeError.self),
      "set(forKey:in:)": .init(thrownErrorType: RimeError.self),
      "removeValue(forKey:in:)": .init(thrownErrorType: RimeError.self),
      "update(signature::for:)": .init(thrownErrorType: RimeError.self),
      "beginMap(forKey:in:)": .init(thrownErrorType: RimeError.self),
      "beginList(forKey:in:)": .init(thrownErrorType: RimeError.self),
      "advanceConfigIterator()": .init(thrownErrorType: RimeError.self),
      "endConfigIterator()": .init(thrownErrorType: RimeError.self),
      "makeConfig()": .init(thrownErrorType: RimeError.self),
      "load(yaml::into:)": .init(thrownErrorType: RimeError.self),
      "createList(forKey:in:)": .init(thrownErrorType: RimeError.self),
      "createMap(forKey:in:)": .init(thrownErrorType: RimeError.self),
      "listSize(forKey:in:)": .init(thrownErrorType: RimeError.self),
      "userID()": .init(thrownErrorType: RimeError.self),
      "userDataSyncDirectory()": .init(thrownErrorType: RimeError.self),
      "input(for:)": .init(thrownErrorType: RimeError.self),
      "set(input::for:)": .init(thrownErrorType: RimeError.self),
      "caretPosition(for:)": .init(thrownErrorType: RimeError.self),
      "set(caretPosition::for:)": .init(thrownErrorType: RimeError.self),
      "version()": .init(thrownErrorType: RimeError.self),
      "selectCandidate(at:for:)": .init(thrownErrorType: RimeError.self),
      "selectCandidateOnCurrentPage(at:for:)": .init(thrownErrorType: RimeError.self),
      "beginCandidates(for:)": .init(thrownErrorType: RimeError.self),
      "advanceCandidateIterator()": .init(thrownErrorType: RimeError.self),
      "endCandidateIterator()": .init(thrownErrorType: RimeError.self),
      "openUserConfig(configId::)": .init(thrownErrorType: RimeError.self),
      "candidateList(fromIndex::for:)": .init(thrownErrorType: RimeError.self),
      "stateLabel(for:state::in:)": .init(thrownErrorType: RimeError.self),
      "stateLabel(for:state::abbreviated::in:)": .init(thrownErrorType: RimeError.self),
      "removeCandidate(at:for:)": .init(thrownErrorType: RimeError.self),
      "removeCandidateOnCurrentPage(at:for:)": .init(thrownErrorType: RimeError.self),
      "highlightCandidate(at:for:)": .init(thrownErrorType: RimeError.self),
      "highlightCandidateOnCurrentPage(at:for:)": .init(thrownErrorType: RimeError.self),
      "page(for:)": .init(thrownErrorType: RimeError.self),
      "sharedDataDirectory()": .init(thrownErrorType: RimeError.self),
      "userDataDirectory()": .init(thrownErrorType: RimeError.self),
      "prebuiltDataDirectory()": .init(thrownErrorType: RimeError.self),
      "stagingDirectory()": .init(thrownErrorType: RimeError.self),
      "syncDirectory()": .init(thrownErrorType: RimeError.self),
    ]
  }
}

#endif
